baseURL = "https://te260ku.github.io/portfolio/"
languageCode = "en-us"
title = "Tetsuro Okuya"
theme = "hugo-cards"
publishDir = "docs"
canonifyurls = true
[params.widgets]
    tags = true
[taxonomies]
    tag = "tags"
    category = "categories"