baseURL = "https://te260ku.github.io/portfolio/"
languageCode = "en-us"
title = "TETSURO OKUYA"
theme = ["hugo-embed-pdf-shortcode", "hugo-cards"]
publishDir = "docs"
canonifyurls = true
enableInlineShortcodes = true
[params.widgets]
    tags = true
[taxonomies]
    tag = "tags"
    category = "categories"